export const COUNTRIES = [
  { code: 'AF', title: 'Afghan' },
  { code: 'AX', title: 'Alandian' },
  { code: 'AL', title: 'Albanian' },
  { code: 'DZ', title: 'Algerian' },
  { code: 'AS', title: 'American Samoan' },
  { code: 'AD', title: 'Andorran' },
  { code: 'AO', title: 'Angolan' },
  { code: 'AI', title: 'Anguillan' },
  { code: 'AQ', title: 'Antarctic' },
  { code: 'AG', title: 'Antiguan/Barbudan' },
  { code: 'AR', title: 'Argentine' },
  { code: 'AM', title: 'Armenian' },
  { code: 'AW', title: 'Aruban' },
  { code: 'AU', title: 'Australian' },
  { code: 'AT', title: 'Austrian' },
  { code: 'AZ', title: 'Azerbaijani' },
  { code: 'BS', title: 'Bahamian' },
  { code: 'BH', title: 'Bahraini' },
  { code: 'BD', title: 'Bangladeshi' },
  { code: 'BB', title: 'Barbadian' },
  { code: 'BY', title: 'Belarusian' },
  { code: 'BE', title: 'Belgian' },
  { code: 'BZ', title: 'Belizean' },
  { code: 'BJ', title: 'Beninese' },
  { code: 'BM', title: 'Bermudian' },
  { code: 'BT', title: 'Bhutanese' },
  { code: 'BO', title: 'Bolivian' },
  { code: 'BA', title: 'Bosnian/Herzegovinian' },
  { code: 'BW', title: 'Motswana' },
  { code: 'BV', title: 'Norwegian' },
  { code: 'BR', title: 'Brazilian' },
  { code: 'IO', title: 'British' },
  { code: 'BN', title: 'Bruneian' },
  { code: 'BG', title: 'Bulgarian' },
  { code: 'BF', title: 'Burkinabe' },
  { code: 'BI', title: 'Burundian' },
  { code: 'KH', title: 'Cambodian' },
  { code: 'CM', title: 'Cameroonian' },
  { code: 'CA', title: 'Canadian' },
  { code: 'CV', title: 'Cape Verdean' },
  { code: 'KY', title: 'Caymanian' },
  { code: 'CF', title: 'Central African' },
  { code: 'TD', title: 'Chadian' },
  { code: 'CL', title: 'Chilean' },
  { code: 'CN', title: 'Chinese' },
  { code: 'CX', title: 'Australian' },
  { code: 'CC', title: 'Cocos Islander' },
  { code: 'CO', title: 'Colombian' },
  { code: 'KM', title: 'Comorian' },
  { code: 'CG', title: 'Congolese' },
  { code: 'CD', title: 'Congolese' },
  { code: 'CK', title: 'Cook Islander' },
  { code: 'CR', title: 'Costa Rican' },
  { code: 'CI', title: 'Ivorian' },
  { code: 'HR', title: 'Croatian' },
  { code: 'CU', title: 'Cuban' },
  { code: 'CY', title: 'Cypriot' },
  { code: 'CZ', title: 'Czech' },
  { code: 'DK', title: 'Danish' },
  { code: 'DJ', title: 'Djiboutian' },
  { code: 'DM', title: 'Dominican' },
  { code: 'DO', title: 'Dominican' },
  { code: 'EC', title: 'Ecuadorian' },
  { code: 'EG', title: 'Egyptian' },
  { code: 'SV', title: 'Salvadoran' },
  { code: 'GQ', title: 'Equatorial Guinean' },
  { code: 'ER', title: 'Eritrean' },
  { code: 'EE', title: 'Estonian' },
  { code: 'ET', title: 'Ethiopian' },
  { code: 'FK', title: 'Falkland Islander' },
  { code: 'FO', title: 'Faroese' },
  { code: 'FJ', title: 'Fijian' },
  { code: 'FI', title: 'Finnish' },
  { code: 'FR', title: 'French' },
  { code: 'GF', title: 'French Guianese' },
  { code: 'PF', title: 'French Polynesian' },
  { code: 'TF', title: 'French' },
  { code: 'GA', title: 'Gabonese' },
  { code: 'GM', title: 'Gambian' },
  { code: 'GE', title: 'Georgian' },
  { code: 'DE', title: 'German' },
  { code: 'GH', title: 'Ghanaian' },
  { code: 'GI', title: 'Gibraltarian' },
  { code: 'GR', title: 'Greek' },
  { code: 'GL', title: 'Greenlandic' },
  { code: 'GD', title: 'Grenadian' },
  { code: 'GP', title: 'Guadeloupean' },
  { code: 'GU', title: 'Guamanian' },
  { code: 'GT', title: 'Guatemalan' },
  { code: 'GG', title: 'Guernsey Islander' },
  { code: 'GN', title: 'Guinean' },
  { code: 'GW', title: 'Bissau-Guinean' },
  { code: 'GY', title: 'Guyanese' },
  { code: 'HT', title: 'Haitian' },
  { code: 'HM', title: 'Australian' },
  { code: 'VA', title: 'Vatican' },
  { code: 'HN', title: 'Honduran' },
  { code: 'HK', title: 'Hong Kong Islander' },
  { code: 'HU', title: 'Hungarian' },
  { code: 'IS', title: 'Icelandic' },
  { code: 'IN', title: 'Indian' },
  { code: 'ID', title: 'Indonesian' },
  { code: 'IR', title: 'Iranian' },
  { code: 'IQ', title: 'Iraqi' },
  { code: 'IE', title: 'Irish' },
  { code: 'IM', title: 'Manx' },
  { code: 'IL', title: 'Israeli' },
  { code: 'IT', title: 'Italian' },
  { code: 'JM', title: 'Jamaican' },
  { code: 'JP', title: 'Japanese' },
  { code: 'JE', title: 'Jersey Islander' },
  { code: 'JO', title: 'Jordanian' },
  { code: 'KZ', title: 'Kazakhstani' },
  { code: 'KE', title: 'Kenyan' },
  { code: 'KI', title: 'I-Kiribati' },
  { code: 'KR', title: 'South Korean' },
  { code: 'KP', title: 'North Korean' },
  { code: 'KW', title: 'Kuwaiti' },
  { code: 'KG', title: 'Kyrgyzstani' },
  { code: 'LA', title: 'Laotian' },
  { code: 'LV', title: 'Latvian' },
  { code: 'LB', title: 'Lebanese' },
  { code: 'LS', title: 'Mosotho' },
  { code: 'LR', title: 'Liberian' },
  { code: 'LY', title: 'Libyan' },
  { code: 'LI', title: 'Liechtenstein' },
  { code: 'LT', title: 'Lithuanian' },
  { code: 'LU', title: 'Luxembourger' },
  { code: 'MO', title: 'Macanese' },
  { code: 'MK', title: 'Macedonian' },
  { code: 'MG', title: 'Malagasy' },
  { code: 'MW', title: 'Malawian' },
  { code: 'MY', title: 'Malaysian' },
  { code: 'MV', title: 'Maldivian' },
  { code: 'ML', title: 'Malian' },
  { code: 'MT', title: 'Maltese' },
  { code: 'MH', title: 'Marshallese' },
  { code: 'MQ', title: 'Martinican' },
  { code: 'MR', title: 'Mauritanian' },
  { code: 'MU', title: 'Mauritian' },
  { code: 'YT', title: 'Mahoran' },
  { code: 'MX', title: 'Mexican' },
  { code: 'FM', title: 'Micronesian' },
  { code: 'MD', title: 'Moldovan' },
  { code: 'MC', title: 'Monegasque' },
  { code: 'MN', title: 'Mongolian' },
  { code: 'ME', title: 'Montenegrin' },
  { code: 'MS', title: 'Montserratian' },
  { code: 'MA', title: 'Moroccan' },
  { code: 'MZ', title: 'Mozambican' },
  { code: 'MM', title: 'Burmese' },
  { code: 'NA', title: 'Namibian' },
  { code: 'NR', title: 'Nauruan' },
  { code: 'NP', title: 'Nepali' },
  { code: 'NL', title: 'Dutch' },
  { code: 'AN', title: 'Dutch' },
  { code: 'NC', title: 'New Caledonian' },
  { code: 'NZ', title: 'New Zealander' },
  { code: 'NI', title: 'Nicaraguan' },
  { code: 'NE', title: 'Nigerien' },
  { code: 'NG', title: 'Nigerian' },
  { code: 'NU', title: 'Niuean' },
  { code: 'NF', title: 'Norfolk Islander' },
  { code: 'MP', title: 'Northern Mariana Islander' },
  { code: 'NO', title: 'Norwegian' },
  { code: 'OM', title: 'Omani' },
  { code: 'PK', title: 'Pakistani' },
  { code: 'PW', title: 'Palauan' },
  { code: 'PS', title: 'Palestinian' },
  { code: 'PA', title: 'Panamanian' },
  { code: 'PG', title: 'Papua New Guinean' },
  { code: 'PY', title: 'Paraguayan' },
  { code: 'PE', title: 'Peruvian' },
  { code: 'PH', title: 'Filipino' },
  { code: 'PN', title: 'Pitcairn Islander' },
  { code: 'PL', title: 'Polish' },
  { code: 'PT', title: 'Portuguese' },
  { code: 'PR', title: 'Puerto Rican' },
  { code: 'QA', title: 'Qatari' },
  { code: 'RE', title: 'Reunionese' },
  { code: 'RO', title: 'Romanian' },
  { code: 'RU', title: 'Russian' },
  { code: 'RW', title: 'Rwandan' },
  { code: 'BL', title: 'Saint Barthelemy Islander' },
  { code: 'SH', title: 'Saint Helenian' },
  { code: 'KN', title: 'Kittitian/Nevisian' },
  { code: 'LC', title: 'Saint Lucian' },
  { code: 'MF', title: 'Saint Martinian' },
  { code: 'PM', title: 'Saint Pierrais' },
  { code: 'VC', title: 'Vincentian' },
  { code: 'WS', title: 'Samoan' },
  { code: 'SM', title: 'Sammarinese' },
  { code: 'ST', title: 'Sao Tomese' },
  { code: 'SA', title: 'Saudi Arabian' },
  { code: 'SN', title: 'Senegalese' },
  { code: 'RS', title: 'Serbian' },
  { code: 'SC', title: 'Seychellois' },
  { code: 'SL', title: 'Sierra Leonean' },
  { code: 'SG', title: 'Singaporean' },
  { code: 'SK', title: 'Slovak' },
  { code: 'SI', title: 'Slovenian' },
  { code: 'SB', title: 'Solomon Islander' },
  { code: 'SO', title: 'Somali' },
  { code: 'ZA', title: 'South African' },
  { code: 'GS', title: 'South Georgian' },
  { code: 'ES', title: 'Spanish' },
  { code: 'LK', title: 'Sri Lankan' },
  { code: 'SD', title: 'Sudanese' },
  { code: 'SR', title: 'Surinamese' },
  { code: 'SJ', title: 'Norwegian' },
  { code: 'SZ', title: 'Swazi' },
  { code: 'SE', title: 'Swedish' },
  { code: 'CH', title: 'Swiss' },
  { code: 'SY', title: 'Syrian' },
  { code: 'TW', title: 'Taiwanese' },
  { code: 'TJ', title: 'Tajikistani' },
  { code: 'TZ', title: 'Tanzanian' },
  { code: 'TH', title: 'Thai' },
  { code: 'TL', title: 'Timorese' },
  { code: 'TG', title: 'Togolese' },
  { code: 'TK', title: 'Tokelauan' },
  { code: 'TO', title: 'Tongan' },
  { code: 'TT', title: 'Trinidadian/Tobagonian' },
  { code: 'TN', title: 'Tunisian' },
  { code: 'TR', title: 'Turkish' },
  { code: 'TM', title: 'Turkmen' },
  { code: 'TC', title: 'Turks and Caicos Islander' },
  { code: 'TV', title: 'Tuvaluan' },
  { code: 'UG', title: 'Ugandan' },
  { code: 'UA', title: 'Ukrainian' },
  { code: 'AE', title: 'Emirati' },
  { code: 'GB', title: 'British' },
  { code: 'US', title: 'American' },
  { code: 'UM', title: 'American' },
  { code: 'UY', title: 'Uruguayan' },
  { code: 'UZ', title: 'Uzbekistani' },
  { code: 'VU', title: 'Vanuatuan' },
  { code: 'VE', title: 'Venezuelan' },
  { code: 'VN', title: 'Vietnamese' },
  { code: 'VG', title: 'Virgin Islander' },
  { code: 'VI', title: 'Virgin Islander' },
  { code: 'WF', title: 'Wallisian' },
  { code: 'EH', title: 'Saharan' },
  { code: 'YE', title: 'Yemeni' },
  { code: 'ZM', title: 'Zambian' },
  { code: 'ZW', title: 'Zimbabwean' },
];
